// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: scan.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScanImage_ScanImage_FullMethodName = "/infodump_temporal.ScanImage/ScanImage"
)

// ScanImageClient is the client API for ScanImage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScanImageClient interface {
	ScanImage(ctx context.Context, in *ScanImageRequest, opts ...grpc.CallOption) (*ScanOutput, error)
}

type scanImageClient struct {
	cc grpc.ClientConnInterface
}

func NewScanImageClient(cc grpc.ClientConnInterface) ScanImageClient {
	return &scanImageClient{cc}
}

func (c *scanImageClient) ScanImage(ctx context.Context, in *ScanImageRequest, opts ...grpc.CallOption) (*ScanOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanOutput)
	err := c.cc.Invoke(ctx, ScanImage_ScanImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScanImageServer is the server API for ScanImage service.
// All implementations must embed UnimplementedScanImageServer
// for forward compatibility.
type ScanImageServer interface {
	ScanImage(context.Context, *ScanImageRequest) (*ScanOutput, error)
	mustEmbedUnimplementedScanImageServer()
}

// UnimplementedScanImageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScanImageServer struct{}

func (UnimplementedScanImageServer) ScanImage(context.Context, *ScanImageRequest) (*ScanOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanImage not implemented")
}
func (UnimplementedScanImageServer) mustEmbedUnimplementedScanImageServer() {}
func (UnimplementedScanImageServer) testEmbeddedByValue()                   {}

// UnsafeScanImageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScanImageServer will
// result in compilation errors.
type UnsafeScanImageServer interface {
	mustEmbedUnimplementedScanImageServer()
}

func RegisterScanImageServer(s grpc.ServiceRegistrar, srv ScanImageServer) {
	// If the following call pancis, it indicates UnimplementedScanImageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScanImage_ServiceDesc, srv)
}

func _ScanImage_ScanImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanImageServer).ScanImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScanImage_ScanImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanImageServer).ScanImage(ctx, req.(*ScanImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScanImage_ServiceDesc is the grpc.ServiceDesc for ScanImage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScanImage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infodump_temporal.ScanImage",
	HandlerType: (*ScanImageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanImage",
			Handler:    _ScanImage_ScanImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scan.proto",
}
