// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: scan.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Image         []byte                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanImageRequest) Reset() {
	*x = ScanImageRequest{}
	mi := &file_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanImageRequest) ProtoMessage() {}

func (x *ScanImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanImageRequest.ProtoReflect.Descriptor instead.
func (*ScanImageRequest) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{0}
}

func (x *ScanImageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScanImageRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ScanImageRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type ScanInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FullFileName  string                 `protobuf:"bytes,3,opt,name=fullFileName,proto3" json:"fullFileName,omitempty"`
	OutPath       string                 `protobuf:"bytes,4,opt,name=outPath,proto3" json:"outPath,omitempty"`
	FileExt       string                 `protobuf:"bytes,5,opt,name=fileExt,proto3" json:"fileExt,omitempty"`
	FileMimeType  string                 `protobuf:"bytes,6,opt,name=fileMimeType,proto3" json:"fileMimeType,omitempty"`
	FileSize      int64                  `protobuf:"varint,7,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanInput) Reset() {
	*x = ScanInput{}
	mi := &file_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanInput) ProtoMessage() {}

func (x *ScanInput) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanInput.ProtoReflect.Descriptor instead.
func (*ScanInput) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{1}
}

func (x *ScanInput) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *ScanInput) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ScanInput) GetFullFileName() string {
	if x != nil {
		return x.FullFileName
	}
	return ""
}

func (x *ScanInput) GetOutPath() string {
	if x != nil {
		return x.OutPath
	}
	return ""
}

func (x *ScanInput) GetFileExt() string {
	if x != nil {
		return x.FileExt
	}
	return ""
}

func (x *ScanInput) GetFileMimeType() string {
	if x != nil {
		return x.FileMimeType
	}
	return ""
}

func (x *ScanInput) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type ScanOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UploadInfo    *ScanInput             `protobuf:"bytes,3,opt,name=uploadInfo,proto3" json:"uploadInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanOutput) Reset() {
	*x = ScanOutput{}
	mi := &file_scan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanOutput) ProtoMessage() {}

func (x *ScanOutput) ProtoReflect() protoreflect.Message {
	mi := &file_scan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanOutput.ProtoReflect.Descriptor instead.
func (*ScanOutput) Descriptor() ([]byte, []int) {
	return file_scan_proto_rawDescGZIP(), []int{2}
}

func (x *ScanOutput) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ScanOutput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScanOutput) GetUploadInfo() *ScanInput {
	if x != nil {
		return x.UploadInfo
	}
	return nil
}

var File_scan_proto protoreflect.FileDescriptor

const file_scan_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"scan.proto\x12\x11infodump_temporal\"L\n" +
	"\x10ScanImageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x14\n" +
	"\x05image\x18\x03 \x01(\fR\x05image\"\xd7\x01\n" +
	"\tScanInput\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12\"\n" +
	"\ffullFileName\x18\x03 \x01(\tR\ffullFileName\x12\x18\n" +
	"\aoutPath\x18\x04 \x01(\tR\aoutPath\x12\x18\n" +
	"\afileExt\x18\x05 \x01(\tR\afileExt\x12\"\n" +
	"\ffileMimeType\x18\x06 \x01(\tR\ffileMimeType\x12\x1a\n" +
	"\bfileSize\x18\a \x01(\x03R\bfileSize\"\x84\x01\n" +
	"\n" +
	"ScanOutput\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12<\n" +
	"\n" +
	"uploadInfo\x18\x03 \x01(\v2\x1c.infodump_temporal.ScanInputR\n" +
	"uploadInfo2^\n" +
	"\tScanImage\x12Q\n" +
	"\tScanImage\x12#.infodump_temporal.ScanImageRequest\x1a\x1d.infodump_temporal.ScanOutput\"\x00B\x03Z\x01.b\x06proto3"

var (
	file_scan_proto_rawDescOnce sync.Once
	file_scan_proto_rawDescData []byte
)

func file_scan_proto_rawDescGZIP() []byte {
	file_scan_proto_rawDescOnce.Do(func() {
		file_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scan_proto_rawDesc), len(file_scan_proto_rawDesc)))
	})
	return file_scan_proto_rawDescData
}

var file_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_scan_proto_goTypes = []any{
	(*ScanImageRequest)(nil), // 0: infodump_temporal.ScanImageRequest
	(*ScanInput)(nil),        // 1: infodump_temporal.ScanInput
	(*ScanOutput)(nil),       // 2: infodump_temporal.ScanOutput
}
var file_scan_proto_depIdxs = []int32{
	1, // 0: infodump_temporal.ScanOutput.uploadInfo:type_name -> infodump_temporal.ScanInput
	0, // 1: infodump_temporal.ScanImage.ScanImage:input_type -> infodump_temporal.ScanImageRequest
	2, // 2: infodump_temporal.ScanImage.ScanImage:output_type -> infodump_temporal.ScanOutput
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scan_proto_init() }
func file_scan_proto_init() {
	if File_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scan_proto_rawDesc), len(file_scan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scan_proto_goTypes,
		DependencyIndexes: file_scan_proto_depIdxs,
		MessageInfos:      file_scan_proto_msgTypes,
	}.Build()
	File_scan_proto = out.File
	file_scan_proto_goTypes = nil
	file_scan_proto_depIdxs = nil
}
